import json
import sys

try:
    from pptx import Presentation
except ModuleNotFoundError as exc:  # pragma: no cover
    raise SystemExit(
        "python-pptx 未安装。请先运行 `pip install python-pptx` 后再重试。"
    ) from exc


def _format_bullets(slide_data):
    bullets = slide_data.get("bullet_points")
    if isinstance(bullets, list) and bullets:
        return "\n".join(str(item) for item in bullets)
    content = slide_data.get("content")
    if isinstance(content, str):
        return content
    return ""


def generate_pptx(title, slides, output_file):
    prs = Presentation()
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    subtitle = slide.placeholders[1]
    subtitle.text = "Auto-generated by Agent PPTX pipeline"

    for slide_data in slides:
        layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = slide_data.get("title", "Untitled Slide")
        slide.placeholders[1].text = _format_bullets(slide_data)

    prs.save(output_file)


if __name__ == "__main__":
    import re
    
    if len(sys.argv) != 2:
        print("Usage: python generate_pptx.py <json_args>")
        sys.exit(1)

    try:
        args = json.loads(sys.argv[1])
    except json.JSONDecodeError:
        print("Error: Invalid JSON argument")
        sys.exit(1)

    title = args.get("title", "Presentation")
    slides = args.get("slides", [])
    
    # Generate output filename
    def _safe_filename(text: str) -> str:
        sanitized = re.sub(r"[^0-9A-Za-z\u4e00-\u9fa5]+", "_", text)
        return sanitized.strip("_") or "presentation"

    output_name = _safe_filename(title)
    output_file = f"{output_name}.pptx"
    
    generate_pptx(title, slides, output_file)
    print(f"Successfully generated PPTX file: {output_file}")

